apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: howlil-app
  namespace: argocd            # ganti kalau ArgoCD-mu pakai namespace lain
spec:
  project: portofolio          # atau 'default' kalau kamu pakai project default

  destination:
    server: https://kubernetes.default.svc
    namespace: portofolio      # namespace Deployment di manifest.yml

  source:
    repoURL: https://github.com/howlil/howlil-app.git
    targetRevision: main
    path: .
    directory:
      recurse: false
      include: manifest.yml    # hanya apply manifest.yml, hindari package.json dll

  syncPolicy:
    automated:
      prune: true
      selfHeal: true