apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: howlil-app
  namespace: portofolio             
spec:
  project: portofolio         

  destination:
    server: https://kubernetes.default.svc
    namespace: portofolio      

  source:
    repoURL: https://github.com/howlil/howlil-app.git
    targetRevision: main
    path: .
    directory:
      recurse: false
      include: manifest.yml    

  syncPolicy:
    automated:
      prune: true
      selfHeal: true